schema_version = "1.0.0"

id = "merge_projects_plus_recipe"
version = "1.0.0"
name = "BIM: MergeProjectsPlus Recipe Installer"
tagline = "Requires Bonsai (BIM) · Installs the MergeProjectsPlus ifcpatch recipe"
maintainer = "Fernando Ferraz Ribeiro <ffribeiro@gmail.com>"
type = "add-on"
tags = ["Import-Export", "Scene"]
website = "https://github.com/ffribeiro/MergeIfcProjectsPlus"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-2.0-or-later"]

[build]
paths_exclude_pattern = [
  ".git/",
  "__pycache__/",
  "*.png",
  "*.zip",
]
